exclude: [config.ru, Gemfile, Gemfile.lock, Rakefile, assets.yml, assets, vendor, bundle]

permalink: pretty

url: http://tv.rymai.me

assets:
  caching:
    path: _cache/assets
  cdn:
    url: http://d1yjw8g5csx279.cloudfront.net/rymai.tv
    # cachebust: hard
